name: s3label_env
dependencies:
- python=3.5.2
- numpy
- pandas=0.20
- psycopg2
- sqlalchemy
- pip
- pytest
- pip:
  - flask
  - flask-cors
  - flask-jwt-extended
  - Pillow
  - opencv-python-headless>=3.4
